### ISSUE TITLE
Ord vs Eq

### ISSUE THREAD

**Issue by PipelineBaron** [Agrosis/joker#5]
Looks like this currently contains an `Ordering` type class but is missing an `Eq` type class. This prevents us from equality comparing two things that aren't necessarily ordered. Can we extract `Eq` to be it's own thing and also if an `Ordering` type class exists for a type then can we automatically derive `Eq` for it?

**Comment by RaasAhsan** [comment]
https://github.com/Agrosis/joker/commit/7a77349c2b7e3380d2a91d1b31cc728d81099f3a

All `Ordering` instances are `Eq` instances now. We could also implement `eq` for them in terms of `lte` and `gte` but there's almost always a more efficient implementation, so I think its better if we force them to implement `eq` in `Ordering`.

**Comment by PipelineBaron** [comment]
Closing.
